### ISSUE TITLE
'no time information in "" (ArgumentError)' issue

### ISSUE THREAD

**Issue by cbucher1** [ttscoff/nvremind#10]
I'm having the following issue whenever I try to run nvremind. I have tried it numerous ways. 

```
Charlie-MacBook-Air:nvremind-master charlesbucher$ ./nvremind.rb -mn ~/Dropbox/Apps/nvNotes/
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/time.rb:327:in `parse': no time information in "" (ArgumentError)
    from ./nvremind.rb:277:in `block (3 levels) in process_command'
    from ./nvremind.rb:271:in `map!'
    from ./nvremind.rb:271:in `block (2 levels) in process_command'
    from ./nvremind.rb:262:in `each'
    from ./nvremind.rb:262:in `block in process_command'
    from ./nvremind.rb:258:in `each'
    from ./nvremind.rb:258:in `process_command'
    from ./nvremind.rb:150:in `run'
    from ./nvremind.rb:404:in `<main>'
Charlie-MacBook-Air:nvremind-master charlesbucher$ 
```

The reminder tag I'm using in my tests is `@remind(2014-11-16 14:00 "Look into Healthcare plans")` and I have tried it without the time, with no luck. The reminder is on its own line. I have tried it with `-m` and `-n` as well as both. I've not been able to find much about the meaning of my error and, honestly, if I knew more about that I could probably crack this a bit easier. Any helpful input would certainly be appreciated. I tried this a couple of months ago, when I first switched to Mac (Finally!!!) with the same problems, but was too busy to pursue a solution. Thanks.

**Comment by gaffcodes** [comment]
Check that there are no "hidden" tags in your notes, e.g., _^remind_, _!remind_, or any other variation of a special character followed by the word _"remind."_
